### PR TITLE
Implement automation for extracting the current and latest version of support workloads

### PR DESCRIPTION
**Pull request by danquah**
#### What does this PR do?
We want to keep track of how far behind we are on keeping things up to date. This can be a somewhat manual process
so to lessen the toil this commit implements an automated process for going through the things we have currently
deployed and getting the current and latest version of the projects.

We're currenly only doing this for the support workloads, and not for Lagoon and AKS.

#### Should this be tested by the reviewer and how?
It should be possible to simply follow the newly created runbook

#### Any specific requests for how the PR should be reviewed?
no

#### What are the relevant tickets?
DDFDRIFT-26

### CODE REVIEW

**Comment by danquah** [comment]
(just ignore the branch-name - i got two changes mixed up 😆 )

**Comment by oliver-reload** [comment]
I noticed that `task ops:get-versions` returns minio version twice, but ran out of time while investigating;
```
- bitnami/minio:
    current: 11.2.15
    latest: 12.2.4
- bitnami/minio:
    current: 11.2.15
    latest: 12.2.4
```
I edited conditional formatting in the versions sheet as Cell C6 was affected by changes to D6.

Other than that; LGTM :+1:

**Review by oliver-reload — APPROVED** [review]
https://github.com/danskernesdigitalebibliotek/dpl-platform/pull/175#issuecomment-1505194869

**Comment by danquah** [comment]
Hah, you're right about mino - it's because of [this](https://github.com/danskernesdigitalebibliotek/dpl-platform/blob/edcada2332b778f553928f472ec6d2ddd4d45007/infrastructure/Taskfile.yml#L196) - we have two installations.

It should be ok for now, I've done a quick verify with the latest changes from main and everything still seems to work, I'll merge.

**Pull request merged**
